spring:
  application:
    name: webApplication
eureka:
  instance:
    #prefer-ip-address: true
    #preferIpAddress: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
logging:
  config: classpath:logback-spring.xml
  path: D:/test/